package com.example.project.model;

import org.springframework.stereotype.Component;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Builder;

@DynamoDBTable(tableName = "MoviesTable")
@Builder
@Component
public class MoviesInfo {
	
	@DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBAttribute
	String title;
	@DynamoDBAttribute
	int publishedYear;
	@DynamoDBAttribute
	String budget;
	@DynamoDBAttribute
	int userReviews;
	@DynamoDBAttribute
	String country;
	@DynamoDBAttribute
	String genre;
	@DynamoDBAttribute
	int duration;
	@DynamoDBAttribute
	String director;
	
	public MoviesInfo() {
		super();
	}
	
	public MoviesInfo(String id, String title, int publishedYear, String budget, int userReviews, String country,
			String genre, int duration, String director) {
		super();
		this.id = id;
		this.title = title;
		this.publishedYear = publishedYear;
		this.budget = budget;
		this.userReviews = userReviews;
		this.country = country;
		this.genre = genre;
		this.duration = duration;
		this.director = director;
	}
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getPublishedYear() {
		return publishedYear;
	}

	public void setPublishedYear(int publishedYear) {
		this.publishedYear = publishedYear;
	}

	public String getBudget() {
		return budget;
	}

	public void setBudget(String budget) {
		this.budget = budget;
	}

	public int getUserReviews() {
		return userReviews;
	}

	public void setUserReviews(int userReviews) {
		this.userReviews = userReviews;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getGenre() {
		return genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	public int getDuration() {
		return duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}
	
	public String getDirector() {
		return director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	@Override
	public String toString() {
		return "MoviesInfo [id=" + id + ", title=" + title + ", publishedYear=" + publishedYear + ", budget=" + budget
				+ ", userReviews=" + userReviews + ", country=" + country + ", genre=" + genre + ", duration="
				+ duration + ", director=" + director + "]";
	}
}
